"""factor-lib-demo 因子目录（82 个）

来源: https://github.com/fifamy/factor-lib-demo @ 1c01589 (data/factor_catalog.json)
提取: data/quantdb/6_ml_datasets/alpha_library/expressions/07_factor_lib_demo.md
字段: code/name_cn/l1/l2/direction/description/formula/wind_source/env_tag/time_tag
      + available（QuantDB 可算性）/ unavailable_reason
"""

FACTORS = [
    {
        "code": "MOM12_1",
        "name_cn": "动量 12-1",
        "l1": "市场交易信息",
        "l2": "动量",
        "direction": 1,
        "description": "过去 252 个交易日剔除最近 21 个交易日的累计对数收益，半衰期 126 加权。",
        "formula": "MOM12_1 = Σ_{k=21}^{252} w_k · ln(P_{t-k+1} / P_{t-k})\n其中 P 为复权收盘价，w_k 为半衰期 126 个交易日的指数权重（越近权重越大），窗口取 [t-252, t-22]（剔除最近 21 个交易日以避开短期反转）。",
        "wind_source": "AShareEODPrices.S_DQ_ADJCLOSE（复权收盘价）",
        "env_tag": "全天候型",
        "time_tag": "近期失效",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "REV1M",
        "name_cn": "短期反转",
        "l1": "市场交易信息",
        "l2": "动量",
        "direction": -1,
        "description": "过去 21 个交易日的累计对数收益（短期反转：高过去收益往往跟随回调）。",
        "formula": "REV1M = ln(P_t / P_{t-21})\n即过去 21 个交易日的累计对数收益（P 为复权收盘价）。方向为负：过去涨多的下期倾向回调。",
        "wind_source": "AShareEODPrices.S_DQ_ADJCLOSE（复权收盘价）",
        "env_tag": "熊市防御型",
        "time_tag": "长期稳定型",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "DASTD",
        "name_cn": "日收益年化波动率",
        "l1": "市场交易信息",
        "l2": "波动",
        "direction": -1,
        "description": "过去 252 个交易日的日对数收益标准差，乘 √252 年化。",
        "formula": "DASTD = std(r_d, 过去 252 个交易日) × √252\n其中 r_d = ln(P_t / P_{t-1}) 为日对数收益（P 为复权收盘价），年化波动率。",
        "wind_source": "AShareEODPrices.S_DQ_ADJCLOSE（复权收盘价）",
        "env_tag": "全天候型",
        "time_tag": "近期失效",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "STOM",
        "name_cn": "月度对数换手率",
        "l1": "市场交易信息",
        "l2": "流动性",
        "direction": -1,
        "description": "过去 21 个交易日换手率之和的对数。换手率 = 成交额 / 流通市值。",
        "formula": "STOM = ln( Σ_{过去 21 个交易日} turnover_d )\nturnover_d = 成交额 / 流通市值，流通市值 = 总市值 × (自由流通股本 / 总股本)。剔除停牌日（成交额=0）。",
        "wind_source": "AShareEODPrices.S_DQ_AMOUNT（成交额）、AShareEODDerivativeIndicator.S_DQ_MV（总市值）、FREE_SHARES_TODAY（自由流通股本）、TOT_SHR_TODAY（总股本）",
        "env_tag": "全天候型",
        "time_tag": "近期失效",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "BETA",
        "name_cn": "历史 Beta",
        "l1": "市场交易信息",
        "l2": "Beta",
        "direction": 1,
        "description": "过去 252 个交易日个股对 cap-weighted 市场组合的回归 Beta。",
        "formula": "BETA = cov(r_i, r_mkt) / var(r_mkt)，过去 252 个交易日 OLS 回归斜率\nr_i 为个股日对数收益；r_mkt 为全市场 cap-weighted 组合日收益，权重 w_j(t-1) = 市值_j(t-1) / Σ市值。",
        "wind_source": "AShareEODPrices.S_DQ_ADJCLOSE（复权收盘价）、AShareEODDerivativeIndicator.S_DQ_MV（总市值，用于市值加权）",
        "env_tag": "熊市防御型",
        "time_tag": "近期转强",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "PE",
        "name_cn": "市盈率PE",
        "l1": "公司内生信息",
        "l2": "估值",
        "direction": -1,
        "description": "PE = 总市值 / TTM归母净利润；越低越便宜。",
        "formula": "市盈率PE = AShareValuationIndicator.S_VAL_PE_TTM（Wind 已算好，月末截面取值）",
        "wind_source": "AShareValuationIndicator.S_VAL_PE_TTM",
        "env_tag": "熊市防御型",
        "time_tag": "近期失效",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "PB",
        "name_cn": "市净率PB",
        "l1": "公司内生信息",
        "l2": "估值",
        "direction": -1,
        "description": "PB = 总市值 / 归母净资产；越低账面估值越便宜。",
        "formula": "市净率PB = AShareValuationIndicator.S_VAL_PB_LF（Wind 已算好，月末截面取值）",
        "wind_source": "AShareValuationIndicator.S_VAL_PB_LF",
        "env_tag": "熊市防御型",
        "time_tag": "近期失效",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "PS",
        "name_cn": "市销率PS",
        "l1": "公司内生信息",
        "l2": "估值",
        "direction": -1,
        "description": "PS = 总市值 / TTM营业收入；适用盈利波动大的成长公司。",
        "formula": "市销率PS = AShareValuationIndicator.S_VAL_PS_TTM（Wind 已算好，月末截面取值）",
        "wind_source": "AShareValuationIndicator.S_VAL_PS_TTM",
        "env_tag": "熊市防御型",
        "time_tag": "近期失效",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "DIVYLD",
        "name_cn": "股息率",
        "l1": "公司内生信息",
        "l2": "估值",
        "direction": 1,
        "description": "近12个月现金分红 / 总市值；越高分红回报越好。",
        "formula": "股息率 = AShareValuationIndicator.S_VAL_DIVIDENDYIELD2（Wind 已算好，月末截面取值）",
        "wind_source": "AShareValuationIndicator.S_VAL_DIVIDENDYIELD2",
        "env_tag": "熊市防御型",
        "time_tag": "近期失效",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "EP",
        "name_cn": "收益市值比",
        "l1": "公司内生信息",
        "l2": "估值",
        "direction": 1,
        "description": "EP = TTM净利润 / 总市值（PE 的倒数）；越高越便宜。",
        "formula": "收益市值比 = DailyValuationFactor.S_DFA_PROFITTOMV（Wind 已算好，月末截面取值）",
        "wind_source": "DailyValuationFactor.S_DFA_PROFITTOMV",
        "env_tag": "熊市防御型",
        "time_tag": "近期失效",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "PE_DED",
        "name_cn": "扣非市盈率",
        "l1": "公司内生信息",
        "l2": "估值",
        "direction": -1,
        "description": "扣除非经常性损益后的 PE(TTM)；剔除一次性损益的估值。",
        "formula": "扣非市盈率 = DailyValuationFactor.S_DFA_PETTM_DEDUCTED（Wind 已算好，月末截面取值）",
        "wind_source": "DailyValuationFactor.S_DFA_PETTM_DEDUCTED",
        "env_tag": "熊市防御型",
        "time_tag": "近期失效",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "EV2EBITDA",
        "name_cn": "EV/EBITDA",
        "l1": "公司内生信息",
        "l2": "估值",
        "direction": -1,
        "description": "总市值 / EBITDA(TTM)；适合跨资本结构比较。",
        "formula": "EV/EBITDA = DailyValuationFactor.S_DFA_MVTOEBITDA（Wind 已算好，月末截面取值）",
        "wind_source": "DailyValuationFactor.S_DFA_MVTOEBITDA",
        "env_tag": "熊市防御型",
        "time_tag": "近期失效",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "ROE",
        "name_cn": "净资产收益率",
        "l1": "公司内生信息",
        "l2": "盈利能力",
        "direction": 1,
        "description": "ROE = TTM归母净利润 / 平均归母净资产；股东资本回报。",
        "formula": "净资产收益率 = PITFinancialFactor（PIT，无未来函数）.S_DFA_ROE_TTM（Wind 已算好，月末截面取值）",
        "wind_source": "PITFinancialFactor（PIT，无未来函数）.S_DFA_ROE_TTM",
        "env_tag": "全天候型",
        "time_tag": "长期稳定型",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "ROA",
        "name_cn": "总资产收益率",
        "l1": "公司内生信息",
        "l2": "盈利能力",
        "direction": 1,
        "description": "ROA = TTM净利润 / 平均总资产；资产盈利效率。",
        "formula": "总资产收益率 = PITFinancialFactor（PIT，无未来函数）.S_DFA_ROA1_TTM（Wind 已算好，月末截面取值）",
        "wind_source": "PITFinancialFactor（PIT，无未来函数）.S_DFA_ROA1_TTM",
        "env_tag": "全天候型",
        "time_tag": "长期稳定型",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "ROIC",
        "name_cn": "投入资本回报率",
        "l1": "公司内生信息",
        "l2": "盈利能力",
        "direction": 1,
        "description": "ROIC = NOPAT / 平均投入资本；投入资本回报。",
        "formula": "投入资本回报率 = PITFinancialFactor（PIT，无未来函数）.S_DFA_ROIC_TTM（Wind 已算好，月末截面取值）",
        "wind_source": "PITFinancialFactor（PIT，无未来函数）.S_DFA_ROIC_TTM",
        "env_tag": "全天候型",
        "time_tag": "长期稳定型",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "GROSSMGN",
        "name_cn": "毛利率",
        "l1": "公司内生信息",
        "l2": "盈利能力",
        "direction": 1,
        "description": "毛利率 = (营收-营业成本)/营收；产品盈利空间。",
        "formula": "毛利率 = PITFinancialFactor（PIT，无未来函数）.S_DFA_GROSSPROFITMARGIN_TTM（Wind 已算好，月末截面取值）",
        "wind_source": "PITFinancialFactor（PIT，无未来函数）.S_DFA_GROSSPROFITMARGIN_TTM",
        "env_tag": "震荡占优型",
        "time_tag": "长期稳定型",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "NETMGN",
        "name_cn": "净利率",
        "l1": "公司内生信息",
        "l2": "盈利能力",
        "direction": 1,
        "description": "净利率 = TTM净利润 / TTM营收；收入转化利润能力。",
        "formula": "净利率 = PITFinancialFactor（PIT，无未来函数）.S_DFA_NETPROFITMARGIN_TTM（Wind 已算好，月末截面取值）",
        "wind_source": "PITFinancialFactor（PIT，无未来函数）.S_DFA_NETPROFITMARGIN_TTM",
        "env_tag": "熊市防御型",
        "time_tag": "长期稳定型",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "OPMGN",
        "name_cn": "营业利润率",
        "l1": "公司内生信息",
        "l2": "盈利能力",
        "direction": 1,
        "description": "营业利润 / 营业收入（≈EBIT Margin）；经营盈利率。",
        "formula": "营业利润率 = PITFinancialFactor（PIT，无未来函数）.S_DFA_OPTOOR_TTM（Wind 已算好，月末截面取值）",
        "wind_source": "PITFinancialFactor（PIT，无未来函数）.S_DFA_OPTOOR_TTM",
        "env_tag": "全天候型",
        "time_tag": "长期稳定型",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "OCF2OR",
        "name_cn": "现金流收入比",
        "l1": "公司内生信息",
        "l2": "盈利质量",
        "direction": 1,
        "description": "经营活动现金流 / 营业收入；利润的现金含量。",
        "formula": "现金流收入比 = PITFinancialFactor（PIT，无未来函数）.S_DFA_OCFTOOR_TTM（Wind 已算好，月末截面取值）",
        "wind_source": "PITFinancialFactor（PIT，无未来函数）.S_DFA_OCFTOOR_TTM",
        "env_tag": "熊市防御型",
        "time_tag": "持续低效",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "NPGROWTH",
        "name_cn": "净利润同比",
        "l1": "公司内生信息",
        "l2": "成长",
        "direction": 1,
        "description": "归母净利润 TTM 同比增速。",
        "formula": "净利润同比 = PITFinancialFactor（PIT，无未来函数）.S_DFA_TTMGROWRATE_NETPROFIT（Wind 已算好，月末截面取值）",
        "wind_source": "PITFinancialFactor（PIT，无未来函数）.S_DFA_TTMGROWRATE_NETPROFIT",
        "env_tag": "震荡占优型",
        "time_tag": "持续低效",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "OPGROWTH",
        "name_cn": "营业利润同比",
        "l1": "公司内生信息",
        "l2": "成长",
        "direction": 1,
        "description": "营业利润 TTM 同比增速。",
        "formula": "营业利润同比 = PITFinancialFactor（PIT，无未来函数）.S_DFA_TTMGROWRATE_OP（Wind 已算好，月末截面取值）",
        "wind_source": "PITFinancialFactor（PIT，无未来函数）.S_DFA_TTMGROWRATE_OP",
        "env_tag": "全天候型",
        "time_tag": "持续低效",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "CFOGROWTH",
        "name_cn": "现金流同比",
        "l1": "公司内生信息",
        "l2": "成长",
        "direction": 1,
        "description": "经营活动现金流 TTM 同比增速。",
        "formula": "现金流同比 = PITFinancialFactor（PIT，无未来函数）.S_DFA_TTMGROWRATE_CFOTT（Wind 已算好，月末截面取值）",
        "wind_source": "PITFinancialFactor（PIT，无未来函数）.S_DFA_TTMGROWRATE_CFOTT",
        "env_tag": "牛市进攻型",
        "time_tag": "长期稳定型",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "LEVERAGE",
        "name_cn": "资产负债率",
        "l1": "公司内生信息",
        "l2": "财务稳健",
        "direction": -1,
        "description": "总负债 / 总资产；越高财务杠杆/风险越大。",
        "formula": "资产负债率 = PITFinancialFactor（PIT，无未来函数）.S_DFA_DEBTTOASSET（Wind 已算好，月末截面取值）",
        "wind_source": "PITFinancialFactor（PIT，无未来函数）.S_DFA_DEBTTOASSET",
        "env_tag": "震荡占优型",
        "time_tag": "近期转强",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "LNMV",
        "name_cn": "对数市值",
        "l1": "公司内生信息",
        "l2": "市值",
        "direction": -1,
        "description": "ln(总市值)；Barra Size 风格因子，A 股小市值历史占优故标负向。",
        "formula": "对数市值 = DailyValuationFactor.S_DFA_LNMV（Wind 已算好，月末截面取值）",
        "wind_source": "DailyValuationFactor.S_DFA_LNMV",
        "env_tag": "震荡占优型",
        "time_tag": "近期转强",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "PCF",
        "name_cn": "市现率PCF",
        "l1": "公司内生信息",
        "l2": "估值",
        "direction": -1,
        "description": "PCF = 总市值 / TTM经营活动现金流；越低现金流估值越便宜。",
        "formula": "市现率PCF = AShareValuationIndicator.S_VAL_PCF_OCFTTM（Wind 已算好，月末截面取值）",
        "wind_source": "AShareValuationIndicator.S_VAL_PCF_OCFTTM",
        "env_tag": "熊市防御型",
        "time_tag": "近期失效",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "OCF2OI",
        "name_cn": "现金流经营收益比",
        "l1": "公司内生信息",
        "l2": "盈利质量",
        "direction": 1,
        "description": "经营活动现金流净额 / 经营活动净收益；经营收益的现金支撑。",
        "formula": "现金流经营收益比 = PITFinancialFactor（PIT，无未来函数）.S_DFA_OCFTOOPERATEINCOME_TTM（Wind 已算好，月末截面取值）",
        "wind_source": "PITFinancialFactor（PIT，无未来函数）.S_DFA_OCFTOOPERATEINCOME_TTM",
        "env_tag": "牛市进攻型",
        "time_tag": "近期失效",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "ACCRUAL",
        "name_cn": "应计利润比",
        "l1": "公司内生信息",
        "l2": "盈利质量",
        "direction": -1,
        "description": "现金流资产比(应计)=(经营现金流-净利润)×2/平均总资产；应计越高质量越差，故负向。",
        "formula": "应计利润比 = PITFinancialFactor（PIT，无未来函数）.S_DFA_ACCA（Wind 已算好，月末截面取值）",
        "wind_source": "PITFinancialFactor（PIT，无未来函数）.S_DFA_ACCA",
        "env_tag": "全天候型",
        "time_tag": "近期转强",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "IMPAIRRISK",
        "name_cn": "减值风险",
        "l1": "公司内生信息",
        "l2": "财务稳健",
        "direction": -1,
        "description": "资产减值损失 / 营业总收入(TTM)；越高减值风险越大，故负向。",
        "formula": "减值风险 = PITFinancialFactor（PIT，无未来函数）.S_DFA_IMPAIRTOGR_TTM（Wind 已算好，月末截面取值）",
        "wind_source": "PITFinancialFactor（PIT，无未来函数）.S_DFA_IMPAIRTOGR_TTM",
        "env_tag": "牛市进攻型",
        "time_tag": "持续低效",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "GMGROWTH",
        "name_cn": "毛利率同比",
        "l1": "公司内生信息",
        "l2": "成长",
        "direction": 1,
        "description": "销售毛利率(TTM)同比变化。",
        "formula": "毛利率同比 = PITFinancialFactor（PIT，无未来函数）.S_DFA_TTMGROWRATE_GM（Wind 已算好，月末截面取值）",
        "wind_source": "PITFinancialFactor（PIT，无未来函数）.S_DFA_TTMGROWRATE_GM",
        "env_tag": "牛市进攻型",
        "time_tag": "持续低效",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "DEDNPGROWTH",
        "name_cn": "扣非净利同比",
        "l1": "公司内生信息",
        "l2": "成长",
        "direction": 1,
        "description": "扣非归母净利润同比增速；剔除一次性损益的真实成长。",
        "formula": "扣非净利同比 = AShareFinancialIndicator（按 ANN_DT PIT as-of 对齐月末）.S_FA_YOYNETPROFIT_DEDUCTED（Wind 已算好，月末截面取值）",
        "wind_source": "AShareFinancialIndicator（按 ANN_DT PIT as-of 对齐月末）.S_FA_YOYNETPROFIT_DEDUCTED",
        "env_tag": "震荡占优型",
        "time_tag": "长期稳定型",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "EQGROWTH",
        "name_cn": "净资产增长率",
        "l1": "公司内生信息",
        "l2": "成长",
        "direction": 1,
        "description": "归母净资产比年初增长率。",
        "formula": "净资产增长率 = AShareFinancialIndicator（按 ANN_DT PIT as-of 对齐月末）.S_FA_YOYEQUITY（Wind 已算好，月末截面取值）",
        "wind_source": "AShareFinancialIndicator（按 ANN_DT PIT as-of 对齐月末）.S_FA_YOYEQUITY",
        "env_tag": "全天候型",
        "time_tag": "近期转强",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "ROEGROWTH",
        "name_cn": "ROE同比",
        "l1": "公司内生信息",
        "l2": "成长",
        "direction": 1,
        "description": "净资产收益率(摊薄)同比变化。",
        "formula": "ROE同比 = AShareFinancialIndicator（按 ANN_DT PIT as-of 对齐月末）.S_FA_YOYROE（Wind 已算好，月末截面取值）",
        "wind_source": "AShareFinancialIndicator（按 ANN_DT PIT as-of 对齐月末）.S_FA_YOYROE",
        "env_tag": "震荡占优型",
        "time_tag": "长期稳定型",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "ORGROWTH",
        "name_cn": "营业收入同比",
        "l1": "公司内生信息",
        "l2": "成长",
        "direction": 1,
        "description": "营业收入同比增速。",
        "formula": "营业收入同比 = AShareFinancialIndicator（按 ANN_DT PIT as-of 对齐月末）.S_FA_YOY_OR（Wind 已算好，月末截面取值）",
        "wind_source": "AShareFinancialIndicator（按 ANN_DT PIT as-of 对齐月末）.S_FA_YOY_OR",
        "env_tag": "震荡占优型",
        "time_tag": "近期转强",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "CURRENT",
        "name_cn": "流动比率",
        "l1": "公司内生信息",
        "l2": "财务稳健",
        "direction": 1,
        "description": "流动资产 / 流动负债；短期偿债能力，越高越稳健。",
        "formula": "流动比率 = AShareFinancialIndicator（按 ANN_DT PIT as-of 对齐月末）.S_FA_CURRENT（Wind 已算好，月末截面取值）",
        "wind_source": "AShareFinancialIndicator（按 ANN_DT PIT as-of 对齐月末）.S_FA_CURRENT",
        "env_tag": "震荡占优型",
        "time_tag": "近期转强",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "QUICK",
        "name_cn": "速动比率",
        "l1": "公司内生信息",
        "l2": "财务稳健",
        "direction": 1,
        "description": "(流动资产-存货) / 流动负债；剔除存货的短期偿债能力。",
        "formula": "速动比率 = AShareFinancialIndicator（按 ANN_DT PIT as-of 对齐月末）.S_FA_QUICK（Wind 已算好，月末截面取值）",
        "wind_source": "AShareFinancialIndicator（按 ANN_DT PIT as-of 对齐月末）.S_FA_QUICK",
        "env_tag": "震荡占优型",
        "time_tag": "近期转强",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "CASHRATIO",
        "name_cn": "保守速动比率",
        "l1": "公司内生信息",
        "l2": "财务稳健",
        "direction": 1,
        "description": "(货币资金+交易性金融资产+应收票据+应收账款+其他应收款)/流动负债。",
        "formula": "保守速动比率 = AShareFinancialIndicator（按 ANN_DT PIT as-of 对齐月末）.S_FA_CASHRATIO（Wind 已算好，月末截面取值）",
        "wind_source": "AShareFinancialIndicator（按 ANN_DT PIT as-of 对齐月末）.S_FA_CASHRATIO",
        "env_tag": "震荡占优型",
        "time_tag": "近期转强",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "INTCOVER",
        "name_cn": "利息保障倍数",
        "l1": "公司内生信息",
        "l2": "财务稳健",
        "direction": 1,
        "description": "已获利息倍数 = EBIT / 利息费用；偿付利息的能力，越高越安全。",
        "formula": "利息保障倍数 = AShareFinancialIndicator（按 ANN_DT PIT as-of 对齐月末）.S_FA_EBITTOINTEREST（Wind 已算好，月末截面取值）",
        "wind_source": "AShareFinancialIndicator（按 ANN_DT PIT as-of 对齐月末）.S_FA_EBITTOINTEREST",
        "env_tag": "全天候型",
        "time_tag": "持续低效",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "DEBT2EQ",
        "name_cn": "产权比率",
        "l1": "公司内生信息",
        "l2": "财务稳健",
        "direction": -1,
        "description": "总负债 / 总权益；越高财务杠杆越大，故负向。",
        "formula": "产权比率 = AShareFinancialIndicator（按 ANN_DT PIT as-of 对齐月末）.S_FA_DEBTTOEQUITY（Wind 已算好，月末截面取值）",
        "wind_source": "AShareFinancialIndicator（按 ANN_DT PIT as-of 对齐月末）.S_FA_DEBTTOEQUITY",
        "env_tag": "震荡占优型",
        "time_tag": "近期转强",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "EQMULT",
        "name_cn": "权益乘数",
        "l1": "公司内生信息",
        "l2": "财务稳健",
        "direction": -1,
        "description": "总资产 / 股东权益 = 1/(1-资产负债率)；越高杠杆越大，故负向。",
        "formula": "权益乘数 = AShareFinancialIndicator（按 ANN_DT PIT as-of 对齐月末）.S_FA_ASSETSTOEQUITY（Wind 已算好，月末截面取值）",
        "wind_source": "AShareFinancialIndicator（按 ANN_DT PIT as-of 对齐月末）.S_FA_ASSETSTOEQUITY",
        "env_tag": "震荡占优型",
        "time_tag": "近期转强",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "OCF2DEBT",
        "name_cn": "现金流负债比",
        "l1": "公司内生信息",
        "l2": "财务稳健",
        "direction": 1,
        "description": "经营活动现金流净额 / 负债合计；偿债的现金保障。",
        "formula": "现金流负债比 = AShareFinancialIndicator（按 ANN_DT PIT as-of 对齐月末）.S_FA_OCFTODEBT（Wind 已算好，月末截面取值）",
        "wind_source": "AShareFinancialIndicator（按 ANN_DT PIT as-of 对齐月末）.S_FA_OCFTODEBT",
        "env_tag": "全天候型",
        "time_tag": "长期稳定型",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "TANG2ASSET",
        "name_cn": "有形资产占比",
        "l1": "公司内生信息",
        "l2": "财务稳健",
        "direction": 1,
        "description": "有形资产 / 总资产；资产质量，无形/商誉占比越低越实。",
        "formula": "有形资产占比 = AShareFinancialIndicator（按 ANN_DT PIT as-of 对齐月末）.S_FA_TANGIBLEASSETSTOASSETS（Wind 已算好，月末截面取值）",
        "wind_source": "AShareFinancialIndicator（按 ANN_DT PIT as-of 对齐月末）.S_FA_TANGIBLEASSETSTOASSETS",
        "env_tag": "震荡占优型",
        "time_tag": "近期转强",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "ASSETTURN",
        "name_cn": "总资产周转率",
        "l1": "公司内生信息",
        "l2": "运营效率",
        "direction": 1,
        "description": "营业总收入 / 平均总资产；资产运用效率。",
        "formula": "总资产周转率 = AShareFinancialIndicator（按 ANN_DT PIT as-of 对齐月末）.S_FA_ASSETSTURN（Wind 已算好，月末截面取值）",
        "wind_source": "AShareFinancialIndicator（按 ANN_DT PIT as-of 对齐月末）.S_FA_ASSETSTURN",
        "env_tag": "全天候型",
        "time_tag": "持续低效",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "INVTURN",
        "name_cn": "存货周转率",
        "l1": "公司内生信息",
        "l2": "运营效率",
        "direction": 1,
        "description": "营业成本 / 平均存货；存货周转速度。",
        "formula": "存货周转率 = AShareFinancialIndicator（按 ANN_DT PIT as-of 对齐月末）.S_FA_INVTURN（Wind 已算好，月末截面取值）",
        "wind_source": "AShareFinancialIndicator（按 ANN_DT PIT as-of 对齐月末）.S_FA_INVTURN",
        "env_tag": "熊市防御型",
        "time_tag": "持续低效",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "ARTURN",
        "name_cn": "应收账款周转率",
        "l1": "公司内生信息",
        "l2": "运营效率",
        "direction": 1,
        "description": "营业收入 / 平均应收账款；回款效率。",
        "formula": "应收账款周转率 = AShareFinancialIndicator（按 ANN_DT PIT as-of 对齐月末）.S_FA_ARTURN（Wind 已算好，月末截面取值）",
        "wind_source": "AShareFinancialIndicator（按 ANN_DT PIT as-of 对齐月末）.S_FA_ARTURN",
        "env_tag": "熊市防御型",
        "time_tag": "持续低效",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "CATURN",
        "name_cn": "流动资产周转率",
        "l1": "公司内生信息",
        "l2": "运营效率",
        "direction": 1,
        "description": "营业总收入 / 平均流动资产。",
        "formula": "流动资产周转率 = AShareFinancialIndicator（按 ANN_DT PIT as-of 对齐月末）.S_FA_CATURN（Wind 已算好，月末截面取值）",
        "wind_source": "AShareFinancialIndicator（按 ANN_DT PIT as-of 对齐月末）.S_FA_CATURN",
        "env_tag": "全天候型",
        "time_tag": "持续低效",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "FATURN",
        "name_cn": "固定资产周转率",
        "l1": "公司内生信息",
        "l2": "运营效率",
        "direction": 1,
        "description": "营业总收入 / 平均固定资产；产能利用效率。",
        "formula": "固定资产周转率 = AShareFinancialIndicator（按 ANN_DT PIT as-of 对齐月末）.S_FA_FATURN（Wind 已算好，月末截面取值）",
        "wind_source": "AShareFinancialIndicator（按 ANN_DT PIT as-of 对齐月末）.S_FA_FATURN",
        "env_tag": "全天候型",
        "time_tag": "长期稳定型",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "REV5D",
        "name_cn": "5日反转",
        "l1": "市场交易信息",
        "l2": "动量",
        "direction": -1,
        "description": "近 5 个交易日累计对数收益（短期反转：近 5 日涨多的下期倾向回调，方向为负）。",
        "formula": "",
        "wind_source": "",
        "env_tag": "全天候型",
        "time_tag": "近期失效",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "MOM60",
        "name_cn": "60日动量",
        "l1": "市场交易信息",
        "l2": "动量",
        "direction": 1,
        "description": "近 60 个交易日（约 3 个月）累计对数收益，中期动量。",
        "formula": "",
        "wind_source": "",
        "env_tag": "全天候型",
        "time_tag": "近期失效",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "MOM20",
        "name_cn": "20日动量",
        "l1": "市场交易信息",
        "l2": "动量",
        "direction": 1,
        "description": "近 20 个交易日（约 1 个月）累计对数收益，短中期动量。",
        "formula": "",
        "wind_source": "",
        "env_tag": "全天候型",
        "time_tag": "近期失效",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "PRICEZ",
        "name_cn": "价格Zscore",
        "l1": "市场交易信息",
        "l2": "均值回复",
        "direction": -1,
        "description": "价格 Zscore：(现价 − 近 60 日均价) / 近 60 日价格标准差；越高越偏离均值，方向负（回复）。",
        "formula": "",
        "wind_source": "",
        "env_tag": "全天候型",
        "time_tag": "近期转强",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "MA20BIAS",
        "name_cn": "均线偏离度",
        "l1": "市场交易信息",
        "l2": "均值回复",
        "direction": -1,
        "description": "均线偏离度：现价 / 近 20 日均价 − 1；正偏离越大越偏贵，方向负（回复）。",
        "formula": "",
        "wind_source": "",
        "env_tag": "全天候型",
        "time_tag": "长期稳定型",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "HLPOS",
        "name_cn": "高低点位置",
        "l1": "市场交易信息",
        "l2": "均值回复",
        "direction": -1,
        "description": "近 60 日高低点位置：(现价 − 60 日最低) / (60 日最高 − 60 日最低)，0~1；越接近高点越负向（回复）。",
        "formula": "",
        "wind_source": "",
        "env_tag": "全天候型",
        "time_tag": "长期稳定型",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "DOWNVOL",
        "name_cn": "下行波动率",
        "l1": "市场交易信息",
        "l2": "波动",
        "direction": -1,
        "description": "下行波动率：近 252 日负收益的标准差 × √252；只看下跌的波动，越高风险越大。",
        "formula": "",
        "wind_source": "",
        "env_tag": "全天候型",
        "time_tag": "近期失效",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "MAXDD1Y",
        "name_cn": "近一年最大回撤",
        "l1": "市场交易信息",
        "l2": "波动",
        "direction": -1,
        "description": "近 252 日最大回撤（按复权价）；回撤越深风险越大，方向负。",
        "formula": "",
        "wind_source": "",
        "env_tag": "牛市进攻型",
        "time_tag": "近期转强",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "RETSKEW",
        "name_cn": "收益偏度",
        "l1": "市场交易信息",
        "l2": "波动",
        "direction": -1,
        "description": "近 252 日日收益偏度；负偏（左尾厚、易暴跌）更差，方向负。",
        "formula": "",
        "wind_source": "",
        "env_tag": "牛市进攻型",
        "time_tag": "近期转强",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "RETKURT",
        "name_cn": "收益峰度",
        "l1": "市场交易信息",
        "l2": "波动",
        "direction": -1,
        "description": "近 252 日日收益峰度；峰度高=极端波动多，方向负。",
        "formula": "",
        "wind_source": "",
        "env_tag": "震荡占优型",
        "time_tag": "长期稳定型",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "BIGDOWN",
        "name_cn": "大跌天数占比",
        "l1": "市场交易信息",
        "l2": "波动",
        "direction": -1,
        "description": "近 60 日大跌天数：单日跌幅 > 5% 的天数占比；越高越脆弱，方向负。",
        "formula": "",
        "wind_source": "",
        "env_tag": "牛市进攻型",
        "time_tag": "近期失效",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "AMOUNT20",
        "name_cn": "对数日均成交额",
        "l1": "市场交易信息",
        "l2": "流动性",
        "direction": -1,
        "description": "近 20 日日均成交额（对数）；大盘高流动性历史溢价低，方向负（偏小流动性）。",
        "formula": "",
        "wind_source": "",
        "env_tag": "牛市进攻型",
        "time_tag": "近期转强",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "TURN20",
        "name_cn": "日均换手率",
        "l1": "市场交易信息",
        "l2": "流动性",
        "direction": -1,
        "description": "近 20 日日均换手率；高换手（投机/拥挤）历史表现弱，方向负。",
        "formula": "",
        "wind_source": "",
        "env_tag": "全天候型",
        "time_tag": "近期失效",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "AMTVOL",
        "name_cn": "成交额波动率",
        "l1": "市场交易信息",
        "l2": "流动性",
        "direction": -1,
        "description": "近 60 日成交额波动率：日成交额的变异系数（std/mean）；越不稳定越负向。",
        "formula": "",
        "wind_source": "",
        "env_tag": "震荡占优型",
        "time_tag": "长期稳定型",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "TURNVOL",
        "name_cn": "换手率波动率",
        "l1": "市场交易信息",
        "l2": "流动性",
        "direction": -1,
        "description": "近 60 日换手率波动率：日换手率标准差；换手忽高忽低=不稳定资金，方向负。",
        "formula": "",
        "wind_source": "",
        "env_tag": "熊市防御型",
        "time_tag": "近期失效",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "PVCORR",
        "name_cn": "价量相关性",
        "l1": "市场交易信息",
        "l2": "价量",
        "direction": -1,
        "description": "近 60 日收益率与成交额的相关性；高正相关=追涨放量（拥挤），方向负。",
        "formula": "",
        "wind_source": "",
        "env_tag": "全天候型",
        "time_tag": "近期转强",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "UPVOLRATIO",
        "name_cn": "上涨日成交占比",
        "l1": "市场交易信息",
        "l2": "价量",
        "direction": -1,
        "description": "近 60 日上涨日成交额占比：上涨日成交额 / 总成交额；过高=放量追涨，方向负。",
        "formula": "",
        "wind_source": "",
        "env_tag": "全天候型",
        "time_tag": "近期失效",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "ABTURN",
        "name_cn": "异常换手率",
        "l1": "市场交易信息",
        "l2": "拥挤度",
        "direction": -1,
        "description": "异常换手率：近 5 日均换手 / 近 60 日均换手 − 1；骤升=短期拥挤，方向负。",
        "formula": "",
        "wind_source": "",
        "env_tag": "全天候型",
        "time_tag": "长期稳定型",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "NPFCST1M",
        "name_cn": "净利预期上修(1M)",
        "l1": "投资者行为信息",
        "l2": "分析师预期",
        "direction": 1,
        "description": "一致预测净利润(未来12月)近1个月的变化率；上修=分析师看好，正向。",
        "formula": "净利预期上修(1M) = ConsensusExpectationFactor.S_WEST_NETPROFIT_FTM_1M（当月值）",
        "wind_source": "ConsensusExpectationFactor.S_WEST_NETPROFIT_FTM_1M",
        "env_tag": "震荡占优型",
        "time_tag": "近期转强",
        "available": False,
        "unavailable_reason": "QuantDB 无一致预期/盈利预测数据",
    },
    {
        "code": "NPFCST3M",
        "name_cn": "净利预期上修(3M)",
        "l1": "投资者行为信息",
        "l2": "分析师预期",
        "direction": 1,
        "description": "一致预测净利润(未来12月)近3个月的变化率。",
        "formula": "净利预期上修(3M) = ConsensusExpectationFactor.S_WEST_NETPROFIT_FTM_3M（当月值）",
        "wind_source": "ConsensusExpectationFactor.S_WEST_NETPROFIT_FTM_3M",
        "env_tag": "震荡占优型",
        "time_tag": "长期稳定型",
        "available": False,
        "unavailable_reason": "QuantDB 无一致预期/盈利预测数据",
    },
    {
        "code": "EPSFCST1M",
        "name_cn": "EPS预期上修(1M)",
        "l1": "投资者行为信息",
        "l2": "分析师预期",
        "direction": 1,
        "description": "一致预测每股收益(FY1)近1个月的变化率。",
        "formula": "EPS预期上修(1M) = ConsensusExpectationFactor.S_WEST_EPS_FY1_1M（当月值）",
        "wind_source": "ConsensusExpectationFactor.S_WEST_EPS_FY1_1M",
        "env_tag": "全天候型",
        "time_tag": "长期稳定型",
        "available": False,
        "unavailable_reason": "QuantDB 无一致预期/盈利预测数据",
    },
    {
        "code": "SALESFCST1M",
        "name_cn": "营收预期上修(1M)",
        "l1": "投资者行为信息",
        "l2": "分析师预期",
        "direction": 1,
        "description": "一致预测营业收入(未来12月)近1个月的变化率。",
        "formula": "营收预期上修(1M) = ConsensusExpectationFactor.S_WEST_SALES_FTM_1M（当月值）",
        "wind_source": "ConsensusExpectationFactor.S_WEST_SALES_FTM_1M",
        "env_tag": "全天候型",
        "time_tag": "近期转强",
        "available": False,
        "unavailable_reason": "QuantDB 无一致预期/盈利预测数据",
    },
    {
        "code": "FCSTGROWTH",
        "name_cn": "预期成长",
        "l1": "投资者行为信息",
        "l2": "分析师预期",
        "direction": 1,
        "description": "一致预测 FY2/FY1 每股收益增速预期；预期成长越高越好。",
        "formula": "预期成长 = ConsensusExpectationFactor.S_WEST_EPS_FYGROWTH（当月值）",
        "wind_source": "ConsensusExpectationFactor.S_WEST_EPS_FYGROWTH",
        "env_tag": "熊市防御型",
        "time_tag": "近期转强",
        "available": False,
        "unavailable_reason": "QuantDB 无一致预期/盈利预测数据",
    },
    {
        "code": "FCSTDISP",
        "name_cn": "盈利预测分歧度",
        "l1": "投资者行为信息",
        "l2": "分析师预期",
        "direction": -1,
        "description": "一致预测 EPS(FY1) 的标准差；分歧越大不确定性越高，方向负。",
        "formula": "盈利预测分歧度 = ConsensusExpectationFactor.S_WEST_STDEPS_FY1（当月值）",
        "wind_source": "ConsensusExpectationFactor.S_WEST_STDEPS_FY1",
        "env_tag": "震荡占优型",
        "time_tag": "近期失效",
        "available": False,
        "unavailable_reason": "QuantDB 无一致预期/盈利预测数据",
    },
    {
        "code": "MAINFLOW",
        "name_cn": "主力净流入强度",
        "l1": "投资者行为信息",
        "l2": "资金流",
        "direction": 1,
        "description": "近20交易日(机构+大户)净流入 / 近20日总成交额；主力资金净买入越强越好。",
        "formula": "主力净流入强度 = AShareMoneyFlow（日频→近20日聚合）.MAINFORCE_NET_RATIO（当月值）",
        "wind_source": "AShareMoneyFlow（日频→近20日聚合）.MAINFORCE_NET_RATIO",
        "env_tag": "震荡占优型",
        "time_tag": "长期稳定型",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "NBRATIO",
        "name_cn": "北向持股占比",
        "l1": "投资者行为信息",
        "l2": "资金流",
        "direction": 1,
        "description": "陆股通(北向)持股占流通股比例；外资偏好，仅覆盖陆股通标的。",
        "formula": "北向持股占比 = SHSCChannelholdings（陆股通持股）.S_RATIO（当月值）",
        "wind_source": "SHSCChannelholdings（陆股通持股）.S_RATIO",
        "env_tag": "全天候型",
        "time_tag": "长期稳定型",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "NBHOLDCHG",
        "name_cn": "北向持股变化",
        "l1": "投资者行为信息",
        "l2": "资金流",
        "direction": 1,
        "description": "北向持股占比的月度变化(本月−上月，百分点)；北向净增持，正向。",
        "formula": "北向持股变化 = SHSCChannelholdings（陆股通持股）.S_RATIO（月度差分）",
        "wind_source": "SHSCChannelholdings（陆股通持股）.S_RATIO",
        "env_tag": "全天候型",
        "time_tag": "长期稳定型",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "HOLDERCHG",
        "name_cn": "股东户数变化",
        "l1": "投资者行为信息",
        "l2": "筹码结构",
        "direction": -1,
        "description": "股东户数月度变化率；户数减少=筹码集中(通常利好)，方向负。",
        "formula": "股东户数变化 = AShareHolderNumber（ANN_DT PIT 对齐）.S_HOLDER_NUM（月度变化率）",
        "wind_source": "AShareHolderNumber（ANN_DT PIT 对齐）.S_HOLDER_NUM",
        "env_tag": "全天候型",
        "time_tag": "长期稳定型",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "HOLDERCONC",
        "name_cn": "户均持股(集中度)",
        "l1": "投资者行为信息",
        "l2": "筹码结构",
        "direction": 1,
        "description": "户均流通股 = 流通股本 / 股东户数；越高=散户越少、筹码越集中，正向。",
        "formula": "户均持股(集中度) = AShareHolderNumber + price_panel（户均流通股，本地算）.PER_HOLDER（当月值）",
        "wind_source": "AShareHolderNumber + price_panel（户均流通股，本地算）.PER_HOLDER",
        "env_tag": "全天候型",
        "time_tag": "近期失效",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "HOLDERCONCCHG",
        "name_cn": "筹码集中度变化",
        "l1": "投资者行为信息",
        "l2": "筹码结构",
        "direction": 1,
        "description": "户均持股的月度变化率；上升=筹码进一步集中，正向。",
        "formula": "筹码集中度变化 = AShareHolderNumber + price_panel（户均流通股，本地算）.PER_HOLDER（月度变化率）",
        "wind_source": "AShareHolderNumber + price_panel（户均流通股，本地算）.PER_HOLDER",
        "env_tag": "震荡占优型",
        "time_tag": "长期稳定型",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "GRCAGR3Y",
        "name_cn": "营收3年复合增速",
        "l1": "公司内生信息",
        "l2": "成长",
        "direction": 1,
        "description": "营业总收入(TTM) 近3年复合年增速 = (今值/36月前值)^(1/3) − 1；持续高成长。",
        "formula": "营业总收入(TTM) 近3年复合年增速 = (今值/36月前值)^(1/3) − 1；持续高成长。",
        "wind_source": "派生（已有数据计算）",
        "env_tag": "全天候型",
        "time_tag": "近期转强",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "PBPCTL",
        "name_cn": "PB历史分位",
        "l1": "公司内生信息",
        "l2": "估值",
        "direction": -1,
        "description": "市净率 PB 在自身过去36个月的分位（0~1）；分位越低=相对自身越便宜，方向负。",
        "formula": "市净率 PB 在自身过去36个月的分位（0~1）；分位越低=相对自身越便宜，方向负。",
        "wind_source": "派生（已有数据计算）",
        "env_tag": "震荡占优型",
        "time_tag": "近期失效",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "RELRET60",
        "name_cn": "相对市场收益",
        "l1": "市场交易信息",
        "l2": "动量",
        "direction": 1,
        "description": "个股近60交易日收益 − 全市场中位收益；跑赢大盘的相对强度。",
        "formula": "个股近60交易日收益 − 全市场中位收益；跑赢大盘的相对强度。",
        "wind_source": "派生（已有数据计算）",
        "env_tag": "全天候型",
        "time_tag": "近期失效",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "RELPEIND",
        "name_cn": "行业相对PE",
        "l1": "公司内生信息",
        "l2": "估值",
        "direction": -1,
        "description": "个股PE − 同行业(申万一级)同截面中位PE；相对行业越便宜越好，方向负。",
        "formula": "个股PE − 同行业(申万一级)同截面中位PE；相对行业越便宜越好，方向负。",
        "wind_source": "派生（已有数据计算）",
        "env_tag": "震荡占优型",
        "time_tag": "长期稳定型",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "RELPBIND",
        "name_cn": "行业相对PB",
        "l1": "公司内生信息",
        "l2": "估值",
        "direction": -1,
        "description": "个股PB − 同行业同截面中位PB；相对行业越便宜越好，方向负。",
        "formula": "个股PB − 同行业同截面中位PB；相对行业越便宜越好，方向负。",
        "wind_source": "派生（已有数据计算）",
        "env_tag": "牛市进攻型",
        "time_tag": "长期稳定型",
        "available": True,
        "unavailable_reason": "",
    },
    {
        "code": "RELRETIND",
        "name_cn": "相对行业收益",
        "l1": "市场交易信息",
        "l2": "动量",
        "direction": 1,
        "description": "个股近60交易日收益 − 同行业均值收益；行业内的相对强度。",
        "formula": "个股近60交易日收益 − 同行业均值收益；行业内的相对强度。",
        "wind_source": "派生（已有数据计算）",
        "env_tag": "全天候型",
        "time_tag": "近期失效",
        "available": True,
        "unavailable_reason": "",
    },
]

BY_CODE = {f["code"]: f for f in FACTORS}

L1_ORDER = []
for _f in FACTORS:
    if _f["l1"] not in L1_ORDER:
        L1_ORDER.append(_f["l1"])
